westport/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import logout


from nabes_app.views import (IndexView, NewsletterListView, CreateAccountView,
ProfileView, ProfileUpdateView, LeadershipListView, DirectoryListView, StreetListView,
directory_printed)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout, name='logout'),
    url(r'^create_account/$', CreateAccountView.as_view(), name='create_account_view'),
    url(r'accounts/profile/$', ProfileView.as_view(), name='profile_view'),
    url(r'accounts/profile/update/$', ProfileUpdateView.as_view(), name='profile_update_view'),
    url(r'^$', IndexView.as_view(), name='index_view'),
    url(r'^newsletter/$', NewsletterListView.as_view(), name='newsletter_listview'),
    url(r'^leadership/$', LeadershipListView.as_view(), name='leadership_listview'),
    url(r'^directory/$', DirectoryListView.as_view(), name='directory_listview'),
    url(r'^streets/$', StreetListView.as_view(), name='street_listview'),
    url(r'^pdf/$', directory_printed, name='pdf_view'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nabes_app/models.py
from django.db import models
from django.contrib.auth.models import User # creates user
from django.db.models.signals import post_save # enables profile attached to user
from django.dispatch import receiver # enables profile attached to user
from django.contrib.staticfiles.templatetags.staticfiles import static # default image for photo_urls


NONE = '----'
ALLISON_COURT = 'Allison Court'
BADGER_RUN = 'Badger Run'
BLADES_TRAIL = 'Blades Trail'
BLUE_WATER_COURT = 'Blue Water Court'
BORDER_CREEK_COURT = 'Border Creek Court'
BRADFORD_LANE = 'Bradford Lane'
BURTON_LANE = 'Burton Lane'
CHAPEL_VIEW_COURT = 'Chapel View Court'
DEER_RUN = 'Deer Run'
DIMPLE_COURT = 'Dimple Court'
FAIRFIELD_FOREST_ROAD = 'Fairfield Forest Road'
FOX_RUN = 'Fox Run'
GOLD_SPRINGS_WAY = 'Gold Springs Way'
GOLF_COURSE_DRIVE_NORTH = 'Golf Course Drive North'
GOLF_COURSE_DRIVE_SOUTH = 'Golf Course Drive South'
GREEN_COVE_COURT = 'Green Cove Court'
HOLLY_COURT = 'Holly Court'
HOWARD_LANE = 'Howard Lane'
ISLAND_VIEW_COURT = 'Island View Court'
LAKE_SHORE_ROAD_NORTH = 'Lake Shore Road North'
LAKE_SHORE_ROAD_SOUTH = 'Lake Shore Road South'
LAKEVIEW_DRIVE = 'Lakeview Drive'
LAS_BRISAS = 'Las Brisas'
MINERS_COVE_COURT = "Miner's Cove Court"
NIBLICK_COURT = 'Niblick Court'
NINE_IRON_COURT = 'Nine Iron Court'
NORMAN_COURT = 'Norman Court'
NORTH_HIGHWAY_16 = 'North Highway 16'
PINE_GLADE_DRIVE = 'Pine Glade Drive'
PLACID_COURT = 'Placid Court'
SAND_WEDGE_COURT = 'Sand Wedge Court'
SHANKLIN_LANE = 'Shanklin Lane'
SHINY_LEAF_DRIVE = 'Shiny Leaf Drive'
THREE_WOOD_DRIVE = 'Three Wood Drive'
WESTCAPE_DRIVE = 'Westcape Drive'
WOODLAND_COURT = 'Woodland Court'
CURRENT = 'Current'
NOT_CURRENT = 'Not Current'
PUBLIC = 'Public'
HIDDEN = 'Hidden'
TOP = 'Top'
MIDDLE = 'Middle'
BOTTOM = 'Bottom'


class Profile(models.Model):
    STREET_CHOICES = (
        (NONE, '----'),
        (ALLISON_COURT, 'Allison Court'),
        (BADGER_RUN, 'Badger Run'),
        (BLADES_TRAIL, 'Blades Trail'),
        (BLUE_WATER_COURT, 'Blue Water Court'),
        (BORDER_CREEK_COURT, 'Border Creek Court'),
        (BRADFORD_LANE, 'Bradford Lane'),
        (BURTON_LANE, 'Burton Lane'),
        (CHAPEL_VIEW_COURT, 'Chapel View Court'),
        (DEER_RUN, 'Deer Run'),
        (DIMPLE_COURT, 'Dimple Court'),
        (FAIRFIELD_FOREST_ROAD, 'Fairfield Forest Road'),
        (FOX_RUN, 'Fox Run'),
        (GOLD_SPRINGS_WAY, 'Gold Springs Way'),
        (GOLF_COURSE_DRIVE_NORTH, 'Golf Course Drive North'),
        (GOLF_COURSE_DRIVE_SOUTH, 'Golf Course Drive South'),
        (GREEN_COVE_COURT, 'Green Cove Court'),
        (HOLLY_COURT, 'Holly Court'),
        (HOWARD_LANE, 'Howard Lane'),
        (ISLAND_VIEW_COURT, 'Island View Court'),
        (LAKE_SHORE_ROAD_NORTH, 'Lake Shore Road North'),
        (LAKE_SHORE_ROAD_SOUTH, 'Lake Shore Road South'),
        (LAKEVIEW_DRIVE, 'Lakeview Drive'),
        (LAS_BRISAS, 'Las Brisas'),
        (MINERS_COVE_COURT, 'Miners Cove Court'),
        (NIBLICK_COURT, 'Niblick Court'),
        (NINE_IRON_COURT, 'Nine Iron Court'),
        (NORMAN_COURT, 'Norman Court'),
        (NORTH_HIGHWAY_16, 'North Highway 16'),
        (PINE_GLADE_DRIVE, 'Pine Glade Drive'),
        (PLACID_COURT, 'Placid Court'),
        (SAND_WEDGE_COURT, 'Sand Wedge Court'),
        (SHANKLIN_LANE, 'Shanklin Lane'),
        (SHINY_LEAF_DRIVE, 'Shiny Leaf Drive'),
        (THREE_WOOD_DRIVE, 'Three Wood Drive'),
        (WESTCAPE_DRIVE, 'Westcape Drive'),
        (WOODLAND_COURT, 'Woodland Court'),
    )
    STATUS_CHOICES = (
        (CURRENT, 'Current'),
        (NOT_CURRENT, 'Not Current'),
    )
    resident = models.OneToOneField('auth.User')
    primary_last_name = models.CharField(max_length=50, default='')
    secondary_last_name = models.CharField(max_length=50, default='', null=True, blank=True)
    primary_phone = models.CharField(max_length=12, default='', help_text='Example: 704-555-4321')
    secondary_phone = models.CharField(max_length=12, default='', null=True, blank=True)
    family_member_names = models.CharField(max_length=200, default='', null=True, blank=True)
    # photo = models.ImageField(upload_to='profile_photos', verbose_name='Profile photo')
    primary_email = models.EmailField(max_length=50, null=True, blank=True)
    house_number = models.PositiveIntegerField(null=True, blank=True)
    street = models.CharField(choices=STREET_CHOICES, max_length=50, default='')
    membership_status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='Current') #make this a choice list
    paypal = models.CharField(max_length=10, default='verify') #capture paypal
    check = models.CharField(max_length=10, default='verify') #manual input
    resident_status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='Current') #make this a choice list to keep directory current

    @property
    def photo_url(self):
        if self.photo:
            return self.photo.url
        return static('nabes_app/img/westport_1.jpg')

    def __str__(self):
        return self.primary_last_name


class PublicPost(models.Model):
    PRIORITY_CHOICES = (
        (TOP, 'Top'),
        (MIDDLE, 'Middle'),
        (BOTTOM, 'Bottom'),
        (HIDDEN, 'Hidden'),
    )
    headline = models.CharField(max_length=60, default='')
    body = models.TextField(max_length=900)
    created = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='post_photos')
    author = models.ForeignKey('auth.User')
    priority = models.CharField(choices=PRIORITY_CHOICES, max_length=10, null=True, blank=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.headline

    @property
    def photo_url(self):
        if self.photo:
            return self.photo.url


class MemberPost(models.Model):
    headline = models.CharField(max_length=60, default='')
    body = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='post_photos')
    author = models.ForeignKey('auth.User')

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ['-created']


class BoardPost(models.Model):
    headline = models.CharField(max_length=60, default='')
    body = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='post_photos')
    author = models.ForeignKey('auth.User')

    def __str__(self):
        return self.headline

    class Meta:
        ordering = ['-created']


class Newsletter(models.Model):
    document = models.FileField(upload_to='documents', max_length=200) # max_length required!!!
    headline = models.CharField(max_length=50, default='Month: Highlight here')
    author = models.ForeignKey('auth.User')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

    @property
    def document_url(self):
        if self.document:
            return self.document.url
        return static('nabes_app/img/newsletter_default.pdf')

class Officer(models.Model):
    title = models.CharField(max_length=50)
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=12)
    email = models.EmailField(max_length=50)
    term = models.CharField(max_length=7)

    def __str__(self):
        return self.name

@receiver(post_save, sender='auth.User')
def create_user_profile(**kwargs):
    created = kwargs.get('created')
    instance = kwargs.get('instance')

    if created:
        Profile.objects.create(resident=instance)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Westport</title>
    <link rel="stylesheet" href="{% static 'nabes_app/css/bootstrap.css' %}" media="screen" title="bootstrap" charset="utf-8">
    <link rel="stylesheet" href="{% static 'nabes_app/css/main.css' %}" >
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div id="wrap">
      <div id="main">

{% block navigation %}
<nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">


      </div>
    </nav>
{% endblock %}

    <div class="container">
        <div class="page-header">
        <h1>Westport Community Association<small>  Celebrating neighbors for 50 years</small></h1>
        <ul class="list-horizontal">
          <li> <a  href="{% url 'index_view' %}">Homepage</a></li>
          {% if request.user.is_authenticated %}

          <li> <a  href={% url 'profile_view' %}>Profile</a></li>
          <li> <a  href="{% url 'newsletter_listview' %}">Newsletters</a></li>
          <li> <a  href="{% url 'logout' %}?next=/">Logout</a></li>

           {% else %}
             <li><a  href={% url 'login' %}>Already registered? Sign in here</a></li>
             {# <a class="btn btn-primary" href={% url 'create_account_view' %}>Create Account</a>#}
           {% endif %}
           {% if request.user.is_staff%}
           <li> <a  href={% url 'directory_listview' %}>Directory</a></li>
           <li> <a  href={% url 'street_listview' %}>StreetList</a></li>
           {% endif %}
        </ul>

      </div>
          {% block content %}
            <p>
              A neighborhood site for the Westport Neighborhood in eastern Lincoln County, NC.
            </p>
          {% endblock %}
        </div>

      </div>

    </div>
    <div id="footer">
      <footer>
        &copy;2017. Built by Hope E. Paasch, <a href="http://www.hepaasch.com">www.hepaasch.com</a>
      </footer>
    </div>

    <script src="//static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">try{ clicky.init(101016603); }catch(e){}</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/101016603ns.gif" /></p></noscript>
  </body>

</html>

templates/directory.html
{% extends "base.html" %}

{% block content %}
  <table class="table table-hover" id="public">
      <th>Primary last name</th>
      <th>Family members</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      {% if request.user.is_staff%}
      <th>Username</th>
      {% endif %}
      <tbody>
      {% for resident in directory_list %}
          <tr>
              <td>{{ resident.primary_last_name }}</td>
              <td>{{ resident.family_member_names }}</td>
              <td><a href="http://maps.google.com/?q={{ resident.house_number}}
                {{ resident.street }}, Denver, NC, 28037">{{ resident.house_number}} {{ resident.street }}</a></td>
              <td><a href="mailto:{{ resident.primary_email }}">{{ resident.primary_email }}</a></td>
              <td><a href="tel:+1-{{ resident.primary_phone }}">{{ resident.primary_phone }}</a></td>
              {% if request.user.is_staff%}
              <td>{{ resident.resident.username }}</td>
              {% endif %}
          </tr>
      {% endfor %}
      </tbody>
  </table>




{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container-fluid">
  <div class="row">

    <div class="col-md-7">
      <div class="thumbnail">
        {% autoescape off %}
          {% for post in top_post_list %}
            <img class="img-responsive" src="{{ post.photo_url }}" alt="Responsive image" />
            <div class="caption">
              <h3>{{ post.headline }}</h3>
              <p>{{ post.body|linebreaks }}</p>
            </div>
          {% endfor %}
          
          {% for post in middle_post_list %}
          <hr>
            <img class="img-responsive"  src="{{ post.photo_url }}" alt="Responsive image" />
            <div class="caption">
              <h3>{{ post.headline }}</h3>
              <p>{{ post.body|linebreaks }}</p>
            </div>
          {% endfor %}
          {% for post in bottom_post_list %}
          <hr>
            <img class="img-responsive" src="{{ post.photo_url }}" alt="Responsive image" />
            <div class="caption">
              <h3>{{ post.headline }}</h3>
              <p>{{ post.body|linebreaks }}</p>
            </div>
          {% endfor %}
        {% endautoescape %}

    </div>
  </div>

    <div class="col-md-5">
      <h2>Join now!</h2>
        <h4>Pay online</h4>
        <ol>
          <li>Pay $40 annual dues with PayPal (no account needed). Plus $1.50 service charge.
            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="7UFKTQL2XXVYW">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
          </li>
          <li>Then <a href={% url 'create_account_view' %}>register here </a>to submit information for the annual directory</a>.</li>
        </ol>

        <h4>Or pay by check</h4>

        <ul>
          <li><a href={% static "nabes_app/img/membership_form.pdf" %} >Click here</a> to print out the membership form.</li>
          <li>Write a check for $40 to the "Westport Community Association."</li>
          <li>Mail or drop off to: <br> WCA treasurer Anke Van Eijk <br> 8030 Island View Court <br> Denver NC 28037</li>
        </ul>

    </div>
  </div>
</div>
{% endblock %}

<h4>Advertise in our newsletter</h4>
<ul>
  <li><a href={% static "nabes_app/img/membership_form.pdf" %} >Click here</a> to print out the advertising form.</li>
  <li>Write a check to the "Westport Community Association."</li>
  <li>Mail or drop off to: <br> WCA treasurer Anke Van Eijk <br> 8030 Island View Court <br> Denver NC 28037</li>
</ul>

templates/leadership.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-2">
  <h3>Association leadership</h3>
    {% for officer in officer_list %}
    <h5> {{ officer.title }}</h5>
    <p> <a href="mailto:{{ officer.email }}">{{ officer.name }}</a></p>
    {% endfor %}

</div>
{% endblock %}

templates/membership_form.html
{% extends "base.html" %}

{% block content %}
<embed src={% url 'nabes_app/img/membership_form.pdf' %} width="1100px" height="1200px" />
{% endblock %}

templates/newsletter.html
{% extends "base.html" %}

{% block content %}
<h3>Our Newsletter</h3>
<p>The Westporter Newsletter is published monthly for paid members. </p>
<p>To submit a news item, email <a href="mailto:ccrowell_pcp@yahoo.com">Candace Crowell</a>.</p>
<p>To purchase an advertisement, email <a href="mailto:anke67@att.net">Anke van Eijk</a>.</p>
<br>
<h4>Click on a month to view that issue of The Westporter:</h4>
  {% for newsletter in newsletter_list %}
  <h5>
    <a href="{{newsletter.document_url}}">{{ newsletter.headline}}</a>
  </h5>
  {% endfor %}
{% endblock %}

templates/pdf.html
NOT USED

templates/street_list.html
{% extends "base.html" %}

{% block content %}
<table class="table table-hover" id="public">
    <th>Address</th>
    <th>Primary last name</th>
    <th>Family members</th>
    <th>Email</th>
    <th>Phone</th>
    <tbody>
    {% for resident in street_list %}
        <tr>
          <td><a href="http://maps.google.com/?q={{ resident.house_number}}
            {{ resident.street }}, Denver, NC, 28037">{{ resident.house_number}}
            {{ resident.street }}</a></td>
          <td>{{ resident.primary_last_name }}</td>
          <td>{{ resident.family_member_names }}</td>
          <td><a href="mailto:{{ resident.primary_email }}">{{ resident.primary_email }}</a></td>
          <td><a href="tel:+1-{{ resident.primary_phone }}">{{ resident.primary_phone }}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<p>to make a pdf, click <a href={% url 'pdf_view' %}>this</a> </p>
{% endblock %}